#!/usr/bin/env bash
# Local-only realistic demo: real 1Password CLI + real GitHub API.
# Not run in CI. Succeeds only when a valid GitHub PAT is stored in 1Password
# and PADE injects it for github.user.read.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PADE="${PADE:-$ROOT/bin/pade}"
MANIFEST="$ROOT/examples/demo-project/pade.yaml"
WHOAMI="$ROOT/examples/demo-project/scripts/github-whoami"
BINDINGS_OUT="${PADE_ONEPASSWORD_BINDINGS:-$ROOT/.pade/bindings.github.live.yaml}"

OP_BIN="${PADE_OP_BIN:-op}"
OP_VAULT="${OP_VAULT:-pade-demo}"
OP_ITEM="${OP_ITEM:-pade-github}"
OP_FIELD="${OP_FIELD:-credential}"

die() {
  echo "error: $*" >&2
  exit 1
}

print_setup() {
  cat >&2 <<EOF
Set up a real GitHub PAT in 1Password, then re-run:

  1. Create a classic PAT with at least the read:user scope:
     https://github.com/settings/tokens

  2. Sign in to the 1Password CLI:
     op signin

  3. Create a vault (once) and item with your PAT in field '${OP_FIELD}':
     op vault create ${OP_VAULT}
     op item create --category=API_Credential --title=${OP_ITEM} --vault=${OP_VAULT} \\
       '${OP_FIELD}[concealed]=YOUR_GITHUB_PAT'

  4. Confirm the ref resolves (prints the token — do this privately):
     op read 'op://${OP_VAULT}/${OP_ITEM}/${OP_FIELD}'

  5. Run:
     make dogfood-github-live

Optional overrides: OP_VAULT, OP_ITEM, OP_FIELD, PADE_ONEPASSWORD_BINDINGS
EOF
}

require_real_op() {
  if [[ "$OP_BIN" == *"fake-op"* ]]; then
    die "PADE_OP_BIN points at fake-op; unset it for the live GitHub demo"
  fi
  if ! command -v "$OP_BIN" >/dev/null 2>&1; then
    die "1Password CLI '$OP_BIN' not found. Install: https://developer.1password.com/docs/cli/get-started/"
  fi
  if ! "$OP_BIN" whoami >/dev/null 2>&1; then
    echo "error: 1Password CLI is not signed in (run: op signin)" >&2
    print_setup
    exit 1
  fi
}

require_item() {
  if ! "$OP_BIN" item get "$OP_ITEM" --vault "$OP_VAULT" >/dev/null 2>&1; then
    echo "error: 1Password item '${OP_ITEM}' not found in vault '${OP_VAULT}'" >&2
    print_setup
    exit 1
  fi
  local ref="op://${OP_VAULT}/${OP_ITEM}/${OP_FIELD}"
  if ! "$OP_BIN" read "$ref" >/dev/null 2>&1; then
    echo "error: cannot read ${ref}" >&2
    print_setup
    exit 1
  fi
  local token
  token="$("$OP_BIN" read "$ref")"
  if [[ -z "$token" ]]; then
    die "1Password field ${ref} is empty"
  fi
  if [[ "$token" == pade-demo-* ]] || [[ "$token" == YOUR_GITHUB_PAT ]]; then
    die "1Password field still has a placeholder/demo token; store a real GitHub PAT"
  fi
}

write_bindings() {
  mkdir -p "$(dirname "$BINDINGS_OUT")"
  cat >"$BINDINGS_OUT" <<EOF
# Generated by scripts/github-live-dogfood.sh — local only (.pade/ is gitignored).
# Contains op:// references, not secret values.
version: "0.1"

capabilities:
  github.user.read:
    provider: onepassword
    onepassword:
      refs:
        GITHUB_TOKEN: "op://${OP_VAULT}/${OP_ITEM}/${OP_FIELD}"
EOF
  echo "Wrote local bindings: $BINDINGS_OUT"
}

run_pade() {
  [[ -x "$PADE" ]] || die "pade binary not found at $PADE (run: make build)"
  chmod +x "$WHOAMI"
  unset GITHUB_TOKEN || true
  export PADE_OP_BIN="$OP_BIN"

  echo "=== pade capabilities (live 1Password → GitHub) ==="
  "$PADE" capabilities -f "$MANIFEST" --bindings "$BINDINGS_OUT" --json >/tmp/pade-github-live-capabilities.json
  if grep -E 'ghp_|github_pat_|gho_|ghu_' /tmp/pade-github-live-capabilities.json >/dev/null; then
    die "capabilities output appears to contain a GitHub token"
  fi
  grep -Eq '"status"[[:space:]]*:[[:space:]]*"available"' /tmp/pade-github-live-capabilities.json \
    || die "expected onepassword capability status available"

  echo "=== pade exec github-whoami (real GitHub API) ==="
  local out
  out="$(
    "$PADE" exec \
      -f "$MANIFEST" \
      --bindings "$BINDINGS_OUT" \
      --capability github.user.read \
      -- "$WHOAMI"
  )"
  echo "$out"
  echo "$out" | grep -q '^login: ' || die "github-whoami did not print login"
  echo "$out" | grep -qv 'stub-user' || die "received stub response; expected real GitHub API"
}

main() {
  require_real_op
  require_item
  write_bindings
  run_pade
  echo "dogfood-github-live: ok"
}

main "$@"
