#!/usr/bin/env bash
# Local-only realistic demo: real Keeper Commander + real GitHub API.
# Not run in CI. Succeeds only when a valid GitHub PAT is stored in Keeper
# and PADE injects it for github.user.read.
#
# Performance: avoid extra Commander round-trips. Commander startup/sync is the
# dominant cost, so we write bindings and run a single pade exec (one resolve).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PADE="${PADE:-$ROOT/bin/pade}"
MANIFEST="$ROOT/examples/demo-project/pade.yaml"
WHOAMI="$ROOT/examples/demo-project/scripts/github-whoami"
BINDINGS_OUT="${PADE_KEEPER_BINDINGS:-$ROOT/.pade/bindings.keeper.live.yaml}"
VENV_KEEPER="$ROOT/.tools/keeper-venv/bin/keeper"

KEEPER_BIN="${PADE_KEEPER_BIN:-}"
KEEPER_RECORD_UID="${KEEPER_RECORD_UID:-}"

die() {
  echo "error: $*" >&2
  exit 1
}

resolve_keeper_bin() {
  if [[ -n "$KEEPER_BIN" ]]; then
    return
  fi
  if command -v keeper >/dev/null 2>&1; then
    KEEPER_BIN="$(command -v keeper)"
    return
  fi
  if [[ -x "$VENV_KEEPER" ]]; then
    KEEPER_BIN="$VENV_KEEPER"
    return
  fi
  die "Keeper Commander not found. Run: make install-keeper-cli"
}

print_setup() {
  cat >&2 <<EOF
Set up a real GitHub PAT in Keeper, then re-run:

  1. Create a classic PAT with at least the read:user scope:
     https://github.com/settings/tokens

  2. Install / sign in to Keeper Commander:
     make install-keeper-cli
     keeper shell
     login <you@example.com>
     # recommended for non-interactive get:
     this-device persistent-login on
     this-device register

  3. Create a Login record whose **password** field is the PAT (not a custom field).
     Copy the record **UID** (Keeper details / \`keeper search <title>\`), not the title.

  4. Export the UID and run:
     export KEEPER_RECORD_UID=<uid>
     make dogfood-keeper-live

Optional overrides: KEEPER_RECORD_UID, PADE_KEEPER_BIN, PADE_KEEPER_BINDINGS
EOF
}

print_field_inventory() {
  echo "field inventory (labels/types only, no values):" >&2
  "$KEEPER_BIN" get --format=json --unmask "$KEEPER_RECORD_UID" </dev/null 2>/dev/null | python3 -c '
import json,sys
raw=sys.stdin.read()
i=raw.find("{")
if i<0:
    print("  (no JSON returned by keeper get --format=json --unmask)", file=sys.stderr); raise SystemExit(0)
doc=json.loads(raw[i:])
print(f"  title={doc.get('title')!r} type={doc.get('type')!r}", file=sys.stderr)
for key in ("fields","custom","custom_fields"):
    for f in doc.get(key) or []:
        if not isinstance(f, dict): continue
        typ=f.get("type"); label=f.get("label") or f.get("name")
        has=bool(f.get("value"))
        print(f"  {key}: type={typ!r} label={label!r} has_value={has}", file=sys.stderr)
' || true
}

require_real_keeper() {
  resolve_keeper_bin
  if [[ "$KEEPER_BIN" == *"fake-keeper"* ]]; then
    die "PADE_KEEPER_BIN points at fake-keeper; unset it for the live Keeper demo"
  fi
  if [[ ! -x "$KEEPER_BIN" ]] && ! command -v "$KEEPER_BIN" >/dev/null 2>&1; then
    die "Keeper Commander '$KEEPER_BIN' not found. Run: make install-keeper-cli"
  fi
}

require_uid() {
  if [[ -z "$KEEPER_RECORD_UID" ]]; then
    echo "error: KEEPER_RECORD_UID is not set" >&2
    print_setup
    exit 1
  fi
}

write_bindings() {
  mkdir -p "$(dirname "$BINDINGS_OUT")"
  cat >"$BINDINGS_OUT" <<EOF
# Generated by scripts/keeper-live-dogfood.sh — local only (.pade/ is gitignored).
# Contains keeper:// references, not secret values.
version: "0.1"

capabilities:
  github.user.read:
    provider: keeper
    keeper:
      refs:
        GITHUB_TOKEN: "keeper://${KEEPER_RECORD_UID}"
EOF
  echo "Wrote local bindings: $BINDINGS_OUT"
}

run_pade() {
  [[ -x "$PADE" ]] || die "pade binary not found at $PADE (run: make build)"
  chmod +x "$WHOAMI"
  unset GITHUB_TOKEN || true
  export PADE_KEEPER_BIN="$KEEPER_BIN"

  echo "=== pade exec github-whoami (live Keeper → GitHub; single Commander resolve) ==="
  local out
  if ! out="$(
    "$PADE" exec \
      -f "$MANIFEST" \
      --bindings "$BINDINGS_OUT" \
      --capability github.user.read \
      -- "$WHOAMI" 2>/tmp/pade-keeper-live-exec.err
  )"; then
    echo "error: pade exec failed" >&2
    # Show non-secret stderr; then field inventory for empty-password cases.
    if [[ -s /tmp/pade-keeper-live-exec.err ]]; then
      grep -vE 'ghp_|github_pat_|gho_|ghu_|ghs_' /tmp/pade-keeper-live-exec.err >&2 || true
    fi
    print_field_inventory
    print_setup
    exit 1
  fi
  echo "$out"
  echo "$out" | grep -q '^login: ' || die "github-whoami did not print login"
  echo "$out" | grep -qv 'stub-user' || die "received stub response; expected real GitHub API"
}

main() {
  require_real_keeper
  require_uid
  write_bindings
  run_pade
  echo "dogfood-keeper-live: ok"
}

main "$@"
