#!/usr/bin/env bash
# Live local demo: resolve capabilities with a real 1Password CLI (`op`).
# Seeds a disposable demo vault/item with fake values, writes local bindings
# under .pade/ (gitignored), then runs pade capabilities + exec.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PADE="${PADE:-$ROOT/bin/pade}"
MANIFEST="$ROOT/examples/demo-project/pade.yaml"
GA_SUMMARY="$ROOT/examples/demo-project/scripts/ga-summary"
BINDINGS_OUT="${PADE_ONEPASSWORD_BINDINGS:-$ROOT/.pade/bindings.onepassword.live.yaml}"

OP_BIN="${PADE_OP_BIN:-op}"
OP_VAULT="${OP_VAULT:-pade-demo}"
OP_ITEM="${OP_ITEM:-pade-google-analytics}"
PROPERTY_VALUE="${PADE_LIVE_PROPERTY_ID:-live-op-demo-property}"
CREDS_VALUE="${PADE_LIVE_CREDENTIALS_PATH:-/tmp/live-op-ga.json}"
SKIP_SEED="${SKIP_SEED:-0}"

die() {
  echo "error: $*" >&2
  exit 1
}

require_real_op() {
  if [[ "$OP_BIN" == *"fake-op"* ]]; then
    die "PADE_OP_BIN points at fake-op; unset it to use the real 1Password CLI"
  fi
  if ! command -v "$OP_BIN" >/dev/null 2>&1; then
    die "1Password CLI '$OP_BIN' not found. Install: https://developer.1password.com/docs/cli/get-started/"
  fi
  if ! "$OP_BIN" whoami >/dev/null 2>&1; then
    cat >&2 <<'EOF'
error: 1Password CLI is not signed in.
  Run:  op signin
  Then: make dogfood-onepassword-live
EOF
    exit 1
  fi
}

ensure_vault() {
  if "$OP_BIN" vault get "$OP_VAULT" >/dev/null 2>&1; then
    echo "Using existing vault: $OP_VAULT"
    return
  fi
  echo "Creating vault: $OP_VAULT"
  "$OP_BIN" vault create "$OP_VAULT" >/dev/null
}

ensure_item() {
  local ref_property="op://${OP_VAULT}/${OP_ITEM}/property_id"
  local ref_creds="op://${OP_VAULT}/${OP_ITEM}/credentials_path"

  if "$OP_BIN" item get "$OP_ITEM" --vault "$OP_VAULT" >/dev/null 2>&1; then
    echo "Updating demo fields on item: $OP_ITEM"
    # Field edit keeps the item; values are intentionally fake demo material.
    "$OP_BIN" item edit "$OP_ITEM" --vault "$OP_VAULT" \
      "property_id[text]=${PROPERTY_VALUE}" \
      "credentials_path[text]=${CREDS_VALUE}" >/dev/null
  else
    echo "Creating demo item: $OP_ITEM (fake values only)"
    "$OP_BIN" item create \
      --category=Password \
      --title="$OP_ITEM" \
      --vault="$OP_VAULT" \
      "property_id[text]=${PROPERTY_VALUE}" \
      "credentials_path[text]=${CREDS_VALUE}" >/dev/null
  fi

  # Sanity-check refs resolve before involving PADE.
  local got
  got="$("$OP_BIN" read "$ref_property")"
  [[ "$got" == "$PROPERTY_VALUE" ]] || die "op read $ref_property returned unexpected value"
  got="$("$OP_BIN" read "$ref_creds")"
  [[ "$got" == "$CREDS_VALUE" ]] || die "op read $ref_creds returned unexpected value"
}

write_bindings() {
  mkdir -p "$(dirname "$BINDINGS_OUT")"
  cat >"$BINDINGS_OUT" <<EOF
# Generated by scripts/onepassword-live-dogfood.sh — local only (.pade/ is gitignored).
# Contains op:// references, not secret values.
version: "0.1"

capabilities:
  google-analytics.read:
    provider: onepassword
    onepassword:
      refs:
        GA_PROPERTY_ID: "op://${OP_VAULT}/${OP_ITEM}/property_id"
        GOOGLE_APPLICATION_CREDENTIALS: "op://${OP_VAULT}/${OP_ITEM}/credentials_path"
EOF
  echo "Wrote local bindings: $BINDINGS_OUT"
}

assert_no_secret_leak() {
  local file="$1"
  if grep -F "$PROPERTY_VALUE" "$file" >/dev/null || grep -F "$CREDS_VALUE" "$file" >/dev/null; then
    die "PADE output appears to contain 1Password credential material: $file"
  fi
}

run_pade() {
  [[ -x "$PADE" ]] || die "pade binary not found at $PADE (run: make build)"
  chmod +x "$GA_SUMMARY"
  unset GA_PROPERTY_ID GOOGLE_APPLICATION_CREDENTIALS GA_ACCESS_TOKEN || true
  export PADE_OP_BIN="$OP_BIN"

  echo "=== pade capabilities (live op) ==="
  "$PADE" capabilities -f "$MANIFEST" --bindings "$BINDINGS_OUT" --json >/tmp/pade-op-live-capabilities.json
  assert_no_secret_leak /tmp/pade-op-live-capabilities.json
  grep -Eq '"status"[[:space:]]*:[[:space:]]*"available"' /tmp/pade-op-live-capabilities.json \
    || die "expected onepassword capability status available"

  echo "=== pade exec ga-summary (live op) ==="
  local out
  out="$(
    "$PADE" exec \
      -f "$MANIFEST" \
      --bindings "$BINDINGS_OUT" \
      --capability google-analytics.read \
      -- "$GA_SUMMARY"
  )"
  echo "$out"
  echo "$out" | grep -q "property_id: ${PROPERTY_VALUE}" \
    || die "ga-summary did not receive property id from 1Password"
  echo "$out" | grep -q "credentials_path: ${CREDS_VALUE}" \
    || die "ga-summary did not receive credentials path from 1Password"
}

main() {
  require_real_op
  if [[ "$SKIP_SEED" != "1" ]]; then
    ensure_vault
    ensure_item
    write_bindings
  else
    [[ -f "$BINDINGS_OUT" ]] || die "SKIP_SEED=1 but bindings file missing: $BINDINGS_OUT"
    echo "SKIP_SEED=1 — using existing bindings: $BINDINGS_OUT"
  fi
  run_pade
  echo "dogfood-onepassword-live: ok"
  echo "Note: demo vault/item '${OP_VAULT}/${OP_ITEM}' uses fake values; delete when finished if desired."
}

main "$@"
